language: python
python:
  - '2.7'
sudo: false
cache:
  directories:
    - "~/.platformio"
install:
  - pip install -U platformio

script:
  - platformio run
before_deploy:
  - for file in .pioenvs/*/firmware.bin; do cp $file ${file%/*}.bin; done
